# Generated by Django 4.2.4 on 2023-09-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2, verbose_name='зима')),
                ('spring', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2, verbose_name='весна')),
                ('summer', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2, verbose_name='лето')),
                ('autumn', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2, verbose_name='осень')),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('beautyTitle', models.CharField(choices=[('poss', 'перевал'), ('gorge', 'ущелье'), ('plateau', 'плато')], max_length=120)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('other_titles', models.CharField(max_length=150)),
                ('connect', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'на рассмотрении'), ('accepted', 'принят'), ('rejected', 'отказан')], default='new', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.category')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sportapp.coords')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='record',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.image'),
        ),
    ]
