# Generated by Django 4.2.4 on 2023-09-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0002_category_coords_perevaladded_remove_image_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='autumn',
            field=models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='spring',
            field=models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='summer',
            field=models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='winter',
            field=models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], max_length=2),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sportapp.category'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='coords',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sportapp.coords'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='images',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sportapp.image'),
        ),
    ]
