# Generated by Django 4.2.4 on 2023-09-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0003_alter_category_autumn_alter_category_spring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.category'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='coords',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sportapp.coords'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.image'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
