# Generated by Django 4.2.4 on 2023-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0004_alter_perevaladded_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevaladded',
            name='area',
            field=models.CharField(choices=[(0, 'Планета Земля'), (1, 'Памиро-Алай'), (2, 'Алтай'), (3, 'Северо-Чуйский хребет'), (4, 'Южно-Чуйский хребет'), (5, 'Катунский хребет'), (6, 'Фанские горы'), (7, 'Гиссарский хребет (участок западнее перевала Анзоб)'), (8, 'Матчинский горный узел'), (9, 'Горный узел Такали, Туркестанский хребет'), (10, 'Высокий Алай'), (11, 'Кичик-Алай и Восточный Алай'), (12, 'Аладаглар'), (13, 'Тавр'), (14, 'Саяны'), (15, 'Хребет Листвяга'), (16, 'Ивановский хребет'), (17, 'Массив Мунгун-Тайга'), (18, 'Хребет Цаган-Шибэту'), (19, 'Хребет Чихачева (Сайлюгем)'), (20, 'Шапшальский хребет'), (21, 'Хребет Южный Алтай'), (22, 'Хребет Монгольский Алтай'), (23, 'Западный Саян'), (24, 'Восточный Саян'), (25, 'Кузнецкий Алатау'), (26, 'Курайский хребет')], default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='type_activity',
            field=models.CharField(choices=[(1, 'пешком'), (2, 'лыжи'), (3, 'катамаран'), (4, 'байдарка'), (5, 'плот'), (6, 'сплав'), (7, 'велосипед'), (8, 'автомобиль'), (9, 'мотоцикл'), (10, 'парус'), (11, 'верхом')], default=''),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='beautyTitle',
            field=models.CharField(choices=[('Poss', 'Перевал'), ('Gorge', 'Ущелье'), ('Plateau', 'Плато'), ('Mountain Peak', 'Вершина горы'), ('Canyon', 'Каньон'), ('Waterfall', 'Водопад'), ('Valley', 'Долина')], max_length=120),
        ),
    ]
