# Generated by Django 4.2.4 on 2023-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0005_perevaladded_area_perevaladded_type_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='type_activity',
            field=models.CharField(choices=[(1, 'пешком'), (2, 'лыжи'), (3, 'катамаран'), (4, 'байдарка'), (5, 'плот'), (6, 'сплав'), (7, 'велосипед'), (8, 'автомобиль'), (9, 'мотоцикл'), (10, 'парус'), (11, 'верхом')]),
        ),
    ]
