# Generated by Django 4.2.4 on 2023-09-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0006_alter_perevaladded_type_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='beautyTitle',
            new_name='beauty_title',
        ),
    ]
