# Generated by Django 4.2.4 on 2023-09-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0008_alter_image_data_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='area',
            field=models.CharField(choices=[('planet_earth', 'Планета Земля'), ('pamir_alai', 'Памиро-Алай'), ('altai', 'Алтай'), ('severo_chuiskiy', 'Северо-Чуйский хребет'), ('yuzhno_chuiskiy', 'Южно-Чуйский хребет'), ('katun', 'Катунский хребет'), ('fanskie_gory', 'Фанские горы'), ('gissarskiy', 'Гиссарский хребет (участок западнее перевала Анзоб)'), ('matchinskiy', 'Матчинский горный узел'), ('turkestanskiy', 'Горный узел Такали, Туркестанский хребет'), ('vysokiy_alai', 'Высокий Алай'), ('kichik_alai', 'Кичик-Алай и Восточный Алай'), ('aladaglar', 'Аладаглар'), ('tavr', 'Тавр'), ('sayany', 'Саяны'), ('listvyaga', 'Хребет Листвяга'), ('ivanovskiy', 'Ивановский хребет'), ('mungun_tayga', 'Массив Мунгун-Тайга'), ('tsagan_shibetu', 'Хребет Цаган-Шибэту'), ('chihacheva', 'Хребет Чихачева (Сайлюгем)'), ('shapshalskiy', 'Шапшальский хребет'), ('yuzhnyy_altay', 'Хребет Южный Алтай'), ('mongolskiy_altay', 'Хребет Монгольский Алтай'), ('zapadnyy_sayan', 'Западный Саян'), ('vostochtnyy_sayan', 'Восточный Саян'), ('kuznetskiy_alatau', 'Кузнецкий Алатау'), ('kurayskiy', 'Курайский хребет')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='type_activity',
            field=models.CharField(choices=[('walking', 'пешком'), ('skiing', 'лыжи'), ('catamaran', 'катамаран'), ('kayak', 'байдарка'), ('raft', 'плот'), ('rafting', 'сплав'), ('bicycle', 'велосипед'), ('car', 'автомобиль'), ('motorcycle', 'мотоцикл'), ('sailing', 'парус'), ('horseback', 'верхом')]),
        ),
    ]
