# Generated by Django 4.2.4 on 2023-09-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0009_alter_perevaladded_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevaladded',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='pereval',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='sportapp.perevaladded'),
            preserve_default=False,
        ),
    ]
