# Generated by Django 4.2.4 on 2023-09-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0010_remove_perevaladded_images_image_pereval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pereval',
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='images',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='sportapp.image'),
            preserve_default=False,
        ),
    ]
