# Generated by Django 4.2.4 on 2023-09-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0011_remove_image_pereval_perevaladded_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='type_activity',
            field=models.CharField(choices=[('walking', 'пешком'), ('skiing', 'лыжи'), ('catamaran', 'катамаран'), ('kayak', 'байдарка'), ('raft', 'плот'), ('rafting', 'сплав'), ('bicycle', 'велосипед'), ('car', 'автомобиль'), ('motorcycle', 'мотоцикл'), ('sailing', 'парус'), ('horseback', 'верхом')], max_length=100),
        ),
    ]
